---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tipsterp/public_html/
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R logos $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp asset-manifest.json $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
